name: Publish Package

on:
  push:
    tags:
      - 'v*'  # 匹配所有以 v 开头的标签

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Node Modules
        with:
          path: node_modules

      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Debug Info
        run: |
          echo "Tag: ${{ github.ref }}"
          echo "Package name: $(jq -r .name package.json)"
          echo "Version: $(jq -r .version package.json)"

      - name: Publish to GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" > .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Publish to npm
        run: |
          sed -i 's/"name": "@Chelase\/sky-tiptap"/"name": "sky-tiptap"/g' package.json
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm publish --access public --registry=https://registry.npmjs.org
          git checkout package.json